Feature/ma 212
GrowthAcceleratorOrg/marketing-cloud-ui pull request #1
Opened 2024-12-10 11:17 UTC by viktor-honcharov-gen

2024-12-10 15:02 UTC, andriivitrenko commented on frontend/automation-status/types.ts
> +}
add new line

2024-12-10 15:03 UTC, andriivitrenko commented on env.example.json
> +}
add new line

2024-12-10 15:08 UTC, andriivitrenko requested changes

2024-12-10 15:08 UTC, andriivitrenko commented on frontend/automations/create-creative-adaptation.tsx
> +  const [errors, setErrors] = useState<object[]>([]);
create interfaces for state

2024-12-10 15:08 UTC, andriivitrenko commented on frontend/custom-ui/block-control.tsx
> +          )
looks like you only compare `choice.name` and `block.category`

2024-12-11 16:30 UTC, olesmarola approved these changes

2024-12-11 16:47 UTC, merged